version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: location-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: vignesh
      MYSQL_DATABASE: location_db
      
      
    ports:
      # host:container (you can change 3307 if you already have MySQL on 3306)
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  locationapi:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: locationapi
    depends_on:
      - db
    environment:
      # SQLAlchemy URL (choose the driver you use)
      # If you're using mysqlclient: "mysql+mysqldb://..."
      # If you're using mysql-connector-python:
      DATABASE_URL: "mysql+mysqlconnector://root:vignesh@db:3306/location_db"
      # Or for PyMySQL:
      # DATABASE_URL: "mysql+pymysql://locationuser:locationpass@db:3306/locationdb"
    ports:
      - "9000:9000"
    volumes:
      - ./locationapi:/app
    command:
volumes:
  mysql_data:

