name: Sonar Cloud Code Analysis
on:
 push:
  branches:
   - main
 pull_request:
  branches:
   - main

   
jobs:
 sonarcloud:
  name: SonarCloudAnalysis
  runs-on: ubuntu-latest
  steps:
   - name: Checkout the code
     uses: actions/checkout@v4
   - name: Set up Python
     uses: actions/setup-python@v5
     with:
      python-version: 3.13.2
   - name: Install Dependecies
     run: |
       python -m pip install --upgrade pip
       pip install -r locationapi/requirements.txt
       pip install coverage
   - name: Run tests with coverage
     run: |
      cd day1
      python -m pytest -vv
      coverage run -m unittest discover
      coverage xml
     continue-on-error: true
   - name: Run SonarCloud Scan
     uses: SonarSource/sonarcloud-github-action@v2.1.1
     with:
      projectBaseDir: .
     env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
